### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by DavidGoodwin**
Hi -- I've changed it to use getopt for argument parsing, so order doesn't matter.
I've also re-indented it...

### CODE REVIEW

**Comment by whereisaaron** [comment]
Thanks @DavidGoodwin the getopt is a nice improvement, but I don't want to mix that with the re-indenting. Besides, we'd have to argument about tabs and space :)

**Comment by DavidGoodwin** [comment]
I can convert it to tabs if you'd rather - it just irked me a little by being both!

(But everyone knows spaces are better....)

**Comment by whereisaaron** [comment]
HI @DavidGoodwin still happy to merge this, just wanted one PR for the parsing improvement, and one PR for the indenting. I agree, spaces are better 😄

**Comment by DavidGoodwin** [comment]
Ah - ok ... I'll work on that and submit them as separate PRs....

**Comment by whereisaaron** [comment]
Thanks @DavidGoodwin, I merged your indenting clean up PR #3.

**Pull request closed without merging**
