### PR TITLE
use proc/meminfo instead of free -m (Fixes Debian Stretch etc)

### PR DESCRIPTION
**Pull request by DavidGoodwin**
https://github.com/eacmen/linux-check-mem-nagios-plugin/commit/a2ca2c2144d2f2fcf19b55f351c1083d63f5a334 - use /proc/meminfo for values instead of free, which is not reliable

### CODE REVIEW

**Comment by whereisaaron** [comment]
I tested it out and compared works well, plus one less process needed.

**Comment by DavidGoodwin** [comment]
Not really - it now runs 4-5 awk processes instead of a single 'free' ...

**Comment by whereisaaron** [comment]
Good point! I made some other changes, to fix the scaling problems with this change (no kB instead of MB) so grab the latest version to test this.

**Comment by DavidGoodwin** [comment]
I've never looked at the .php file, so wasn't sure whether changing the units from the shell script would mess it up or not .... but fine - all these merges mean I can drop my copy/forks/changes. 

Thanks for accepting/merging everything so quickly.

**Comment by whereisaaron** [comment]
Actually I just adjusted the internal scaling to make sure the output units were the same as before; MB for the human message, and Bytes for the Nagios performance data (for the chart).

Thanks for the contributions!

**Pull request merged**
